---
apiVersion: apps/v1 
kind: Deployment
metadata: 
  name: hello-world-go
  labels: 
      name: "hello-world"

spec:
  replicas: 1
  selector:
    matchLabels:
      app: "hello-world-go"
  template:
    metadata:
      name: hello-world
      labels:
        app: hello-world-go
    spec:
      containers:
        - image: richarddoggo/hello-world-go:0.0.1 # this would start repository digest checks
          imagePullPolicy: Always 
          name: hello-world-go
          command: ["/server"]
          ports:
            - containerPort: 8080       
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 10
          securityContext:
            privileged: true
