apiVersion: v1
kind: Service
metadata:
  name: hello-world
  labels:
    app: hello-world-go 
  namespace: hello-world 
spec:
  clusterIP: None
  ports:
  - port: 8080 
    name: endpoint
  selector:
    app: hello-world-go 
